### ISSUE TITLE
Update build guide

### ISSUE THREAD

**Issue by NicolasVuaille** [JonasLukasczyk/paraview-node-editor#1]
The readme mention to copy the plugin source into paraview sources, and then build all once.

This is not the recommended way. Please do so:
 - build ParaView alone
 - build the plugin in its own directory. At configuration time, pass `-DParaView_DIR=/path/to/pv/build`
That way, paraview sources stay clean, and it is easier to update either pv and the plugin.

At runtime, you will need to `load new` plugin, and look for `NodeEditor.so` under in paraview-node-editor/build/lib/paraview-5.8/plugins/NodeEditor

**Comment by JonasLukasczyk** [comment]
Hi Nicolas,
thanks! This is much better. I adjusted the ReadMe. If you think it is clear enough we can close this issue.

Best
